FROM node:20
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
# Google Cloud Run จะส่งพอร์ตมาให้ผ่าน Environment Variable ชื่อ PORT
ENV PORT=8080
EXPOSE 8080
CMD [ "node", "server.js" ]